version: "3.9"

services:
  question-service:
    build: ./question-service
    container_name: question-service-dev
    ports:
      - "8000:8000"
    volumes:
      - ./question-service:/usr/src/app
      - /usr/src/app/node_modules 
    env_file:
      - ./question-service/.env
    environment:
      - NODE_ENV=development
    command: npm run start

  user-service:
    build: ./user-service
    container_name: user-service-dev
    ports:
      - "3001:3001"
    volumes:
      - ./user-service:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./user-service/.env
    environment:
      - NODE_ENV=development
    command: npm start