version: "3.9"

services:
  question-service:
    build: ./question-service
    container_name: question-service-dev
    ports:
      - "8000:8000"
    volumes:
      - ./question-service:/usr/src/app
      - /usr/src/app/node_modules 
    env_file:
      - ./question-service/.env
    environment:
      - NODE_ENV=development
    command: npm run start
    networks:
      - app-network

  user-service:
    build: ./user-service
    container_name: user-service-dev
    ports:
      - "3001:3001"
    volumes:
      - ./user-service:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./user-service/.env
    environment:
      - NODE_ENV=development
    command: npm start
    networks:
      - app-network

  match-service:
    build:
      context: ./match-service
      dockerfile: Dockerfile
    container_name: match-service-dev
    ports:
      - "3002:3002"
    volumes:
      - ./match-service:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./match-service/.env
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: npm run start:dev
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

  collab-service:
    build: ./collaboration-service
    container_name: collab-service-dev
    ports:
      - "3005:3005"
    volumes:
      - ./collaboration-service:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./collaboration-service/.env
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: npm run start:dev
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis_data: