# Specify the version of the Docker Compose.
version: "3.9"

# Define the services and applications that make up your application.
services:
  question-service:
    build: .
    container_name: question-service-dev
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules 
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    command: npm run start:dev